[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXTAUTH_URL = "https://delphincleanair.org"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-server-handler/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-server-handler/:splat"
  status = 200
